"""
report_generator.py (Recon Tool)
---------------------------------
Renders a ReconResult into a self-contained HTML report, and optionally a
PDF via WeasyPrint. Generic helpers turn arbitrary dict/list module output
into readable tables without needing bespoke rendering code per module.
"""

from __future__ import annotations

import html
import os
from typing import Any

from recon import ReconResult

MODULE_TITLES = {
    "whois": "WHOIS Lookup",
    "dns": "DNS Record Enumeration",
    "subdomains": "Subdomain Enumeration",
    "ssl": "SSL/TLS Certificate",
    "http_headers": "HTTP Response Headers",
    "robots_txt": "robots.txt Analysis",
    "sitemap": "sitemap.xml Discovery",
    "technology": "Technology Fingerprinting",
    "screenshot": "Screenshot",
    "port_scan": "Open Port Scan",
}


def _esc(v) -> str:
    return html.escape(str(v)) if v is not None else ""


def _render_value(value: Any) -> str:
    if value is None:
        return "<em>none</em>"
    if isinstance(value, bool):
        return "Yes" if value else "No"
    if isinstance(value, (list, tuple)):
        if not value:
            return "<em>none</em>"
        if all(isinstance(v, dict) for v in value):
            return _render_dict_list(value)
        items = "".join(f"<li>{_esc(v)}</li>" for v in value)
        return f"<ul class='val-list'>{items}</ul>"
    if isinstance(value, dict):
        return _render_dict(value)
    return _esc(value)


def _render_dict(d: dict) -> str:
    rows = "".join(
        f"<tr><th>{_esc(k)}</th><td>{_render_value(v)}</td></tr>"
        for k, v in d.items()
        if not str(k).startswith("_")
    )
    return f"<table class='kv'>{rows}</table>"


def _render_dict_list(items: list) -> str:
    if not items:
        return "<em>none</em>"
    keys = list(items[0].keys())
    header = "".join(f"<th>{_esc(k)}</th>" for k in keys)
    rows = "".join(
        "<tr>" + "".join(f"<td>{_render_value(row.get(k))}</td>" for k in keys) + "</tr>"
        for row in items
    )
    return f"<table class='grid'><thead><tr>{header}</tr></thead><tbody>{rows}</tbody></table>"


def _module_section(module_key: str, data: Any) -> str:
    title = MODULE_TITLES.get(module_key, module_key.replace("_", " ").title())
    if isinstance(data, dict) and data.get("error"):
        body = f"<p class='error'>{_esc(data['error'])}</p>"
    else:
        body = _render_value(data)
    return f"""
    <section class="module">
      <h2>{_esc(title)}</h2>
      {body}
    </section>
    """


def render_body(result: ReconResult) -> str:
    """Render just the report content (no <html>/<head> wrapper), reusable
    both for the standalone report and for the inline web-UI preview."""
    if result.error:
        return f"<p class='error'>Reconnaissance failed: {_esc(result.error)}</p>"

    meta = f"""
    <table class="kv">
      <tr><th>Target</th><td>{_esc(result.target)}</td></tr>
      <tr><th>Resolved Hostname</th><td>{_esc(result.hostname)}</td></tr>
      <tr><th>Base URL</th><td>{_esc(result.base_url)}</td></tr>
      <tr><th>Generated</th><td>{_esc(result.generated_at)}</td></tr>
    </table>
    """
    sections = "".join(_module_section(key, val) for key, val in result.modules.items())
    return meta + sections


def render_html(result: ReconResult) -> str:
    body = render_body(result)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Web Application Reconnaissance Report</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, Arial, sans-serif; margin:0; background:#f3f4f6; color:#111827; }}
  .container {{ max-width: 1000px; margin: 0 auto; padding: 32px; }}
  h1 {{ font-size: 22px; margin-bottom: 4px; }}
  h2 {{ font-size: 15px; margin: 0 0 10px; color:#1f2937; }}
  section.module {{ background:white; border-radius:8px; padding:16px 20px; margin-bottom:16px; box-shadow:0 1px 2px rgba(0,0,0,.06); }}
  table.kv {{ width:100%; border-collapse:collapse; margin-bottom: 8px;}}
  table.kv th {{ text-align:left; width:200px; padding:6px 8px; color:#374151; font-size:13px; vertical-align:top; border-bottom:1px solid #f0f0f0;}}
  table.kv td {{ padding:6px 8px; font-size:13px; border-bottom:1px solid #f0f0f0; word-break:break-word;}}
  table.grid {{ width:100%; border-collapse:collapse; font-size:12.5px; }}
  table.grid th, table.grid td {{ border:1px solid #e5e7eb; padding:6px 8px; text-align:left; }}
  table.grid th {{ background:#f9fafb; }}
  ul.val-list {{ margin:4px 0; padding-left:18px; font-size:13px; }}
  .error {{ color:#b91c1c; font-weight:600; }}
  footer {{ margin-top: 24px; font-size:11px; color:#9ca3af; text-align:center; }}
</style>
</head>
<body>
<div class="container">
  <h1>Web Application Reconnaissance Report</h1>
  {body}
  <footer>Generated by Web Application Reconnaissance Tool &mdash; for authorized security assessments only.</footer>
</div>
</body>
</html>"""


def render_pdf(result: ReconResult, output_path: str) -> str:
    try:
        from weasyprint import HTML
    except ImportError as exc:
        raise ImportError(
            "PDF export requires WeasyPrint and its system dependencies "
            "(Pango, Cairo, GDK-Pixbuf). Install via 'pip install weasyprint'."
        ) from exc

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    HTML(string=render_html(result)).write_pdf(output_path)
    return output_path
